spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdatabase
    username: root
    password: pedro
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true